# Generated by Django 3.1.4 on 2021-08-17 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(default='')),
                ('client', models.CharField(default='', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('url', models.URLField(default='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.workcategory')),
            ],
        ),
    ]
