# Generated by Django 3.1.4 on 2021-08-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredworks',
            name='file',
            field=models.FileField(null=True, upload_to='static/featured_works'),
        ),
        migrations.AlterField(
            model_name='featuredworks',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
