# Generated by Django 3.1.4 on 2021-08-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20210817_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredworks',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='featuredworks',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/featured_works'),
        ),
    ]
